# Generated by Django 4.1.7 on 2023-03-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_reservation_options_alter_reservation_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='visit_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
