# Generated by Django 4.1.7 on 2023-03-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_reservation_visit_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='visit_datetime',
            field=models.DateTimeField(),
        ),
    ]
